### ISSUE TITLE
Build in Mac fails due to lack of full path to libtinyxml.a

### ISSUE THREAD

**Issue by senthilmanick** [ros2/tinyxml_vendor#6] opened 2017-09-25 17:13 UTC
Using the latest, the link lines for many dependent packages don't get the full path to library
For example, rcl_lifecycle gets the link line as ...
[snip]ros2_ws/install/lib/librcutils.dylib -ltinyxml2 

It should rather be 
[snip]ros2_ws/install/lib/librcutils.dylib ros2_ws/install/lib/libtinyxml.a

**Comment by dirk-thomas** [comment] 2017-09-25 18:29
Can you please include the exact steps you are using (as well as relevant version numbers of related packages) in order to reproduce the problem.

**Comment by senthilmanick** [comment] 2017-09-28 23:00
tinyxml2: stable 5.0.1 (bottled), HEAD
Improved tinyxml (in memory efficiency and size)
http://grinninglizard.com/tinyxml2
/usr/local/Cellar/tinyxml2/5.0.1 (11 files, 148.8KB) *
  Poured from bottle on 2017-09-25 at 09:30:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tinyxml2.rb
==> Dependencies
Build: cmake ✔

src/ament/ament_tools/scripts/ament.py build --symlink-install

Looks like the call to find_package_handle_standard_args in cmake/Modules/FindTinyXML.cmake is wrong…shouldn’t it be:
find_package_handle_standard_args(TinyXML 
    FOUND_VAR TinyXML_FOUND
    REQUIRED_VARS
      TinyXML_INCLUDE_DIR
      TinyXML_LIBRARY
  )

**Comment by dirk-thomas** [comment] 2017-09-28 23:34
@senthilmanick Can you create a PR with the proposed patch and try if that makes it work for you.

This code snippet was never reviewed in a PR afaik. Maybe @Karsten1987 can comment on this since he wrote the code.

**Comment by mikaelarguedas** [comment] 2017-09-28 23:42
I think that there is a confusion between `tinyxml` and `tinyxml2` here. These are 2 different packages.
`tinyxml2` is used by one of our dependencies and is a system dependency not part of the ros2 workspace.
`tinyxml` is used by a handful of demo packages and is cloned and built in the ros2 workspace for MacOS, though it is used only by a handful of demos and nothing in the core of ROS 2 links against it AFAIK.

In your case it seems that it's trying to link against `tinyxml2`
Thus it should not be in `ros2_ws/install/lib` but in your system libraries. `-ltinyxml2` is because it is an exported target (I would guess coming from [here](https://github.com/eProsima/Fast-RTPS/blob/687150ade2919587e2211f68730f4972ac857152/cmake/modules/FindTinyXML2.cmake#L13)). 

Though I'm confused and can't find a reason for `rcl_lifecycle` to link against tinyxml2

**Comment by mikaelarguedas** [comment] 2017-10-16 15:19
@senthilmanick A similar issue has been solved by disabling SIP on MacOS. I'm going to close this in favor of https://github.com/ros2/ros2/issues/409. Feel free to comment here if the solution presented in https://github.com/ros2/ros2/issues/409 doesn't solve the issue for you

**Closed as completed by mikaelarguedas** 2017-10-16 15:19 UTC
Labels: more-information-needed

**Comment by dhood** [comment] 2017-10-16 15:41
@mikaelarguedas @senthilmanick in the end disabling SIP was only required at runtime. The issue linking against the targets was resolved by installing/upgrading the xcode command-line tools: https://github.com/ros2/build_cop/issues/58
(I'll update the first post of ros2/ros2#409 since it's misleading as is if you miss the comments.)
